name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Previous steps remain the same...
      
      - name: Build with Buildozer
        run: |
          export PATH="$PATH:~/.local/bin:$ANDROID_HOME/build-tools/36.0.0"
          
          # Get Java home from installed JDK
          JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))
          echo "Using JAVA_HOME: $JAVA_HOME"
          
          # Force accept all licenses
          mkdir -p "$ANDROID_HOME/licenses"
          echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
          echo -e "84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
          echo -e "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"
          
          # Initialize python-for-android first
          buildozer -v init
          
          # Build with debug output
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PDFEditor-debug-apk
          path: bin/*.apk
